# Generated by Django 3.2 on 2022-03-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='beertoken',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=6),
        ),
    ]
